apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments
  labels:
    app: comments
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: comments
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
        - name: comments
          image: eddyzheng/comments
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: comments
spec:
  selector:
    app: comments
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080