apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts
  labels:
    app: posts
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: posts
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: eddyzheng/posts
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: posts
spec:
  selector:
    app: posts
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080