apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  labels:
    app: users
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: users
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: eddyzheng/users
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: users
spec:
  selector:
    app: users
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080